name: Merge Dependabot PR

on:
  pull_request:
    branches:
      - main

run-name: Merge Dependabot PR ${{ github.ref_name }}

jobs:
  merge-dependabot-pr:

    uses: spring-io/spring-github-workflows/.github/workflows/spring-merge-dependabot-pr.yml@main
    secrets:
      GH_ACTIONS_REPO_TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}