name: Merge Dependabot PR

on:
  pull_request:
    branches:
      - main

run-name: Merge Dependabot PR ${{ github.ref_name }}

jobs:
  merge-dependabot-pr:
    permissions: write-all

    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:

      - name: Merge Dependabot pull request
        run: gh api -X PUT repos/$GITHUB_REPOSITORY/pulls/${{ github.event.pull_request.number }}/merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

