name: Pull Request Build with Gradle

on:
  workflow_call:

jobs:
  build-pr:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          show-progress: false

      - uses: spring-io/spring-gradle-build-action@v2

      - name: Run Pull Request Build
        run: gradle check

      - name: Capture Test Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '*/build/reports/tests/**/*.*'
          retention-days: 3
